# Generated by Django 3.1.1 on 2020-09-25 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_surname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unspecified')], max_length=1)),
                ('email', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=50)),
                ('birth_date', models.DateField(verbose_name='Date of birth')),
                ('tax_code', models.CharField(max_length=16)),
                ('r_address_is_validated', models.BooleanField(default=False, verbose_name='Residence address is validated')),
                ('r_route', models.CharField(blank=True, max_length=200, null=True)),
                ('r_street_number', models.CharField(blank=True, max_length=200, null=True)),
                ('r_locality', models.CharField(blank=True, max_length=200, null=True)),
                ('r_administrative_area_level_3', models.CharField(blank=True, max_length=200, null=True)),
                ('r_administrative_area_level_2', models.CharField(blank=True, max_length=200, null=True)),
                ('r_administrative_area_level_1', models.CharField(blank=True, max_length=200, null=True)),
                ('r_country', models.CharField(blank=True, max_length=200, null=True)),
                ('r_postal_code', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('r_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='airpoll.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='airpoll.contact')),
            ],
        ),
    ]
