# Generated by Django 3.1.1 on 2020-09-25 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpoll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='airpoll.contact')),
            ],
        ),
    ]
