# Generated by Django 3.1.1 on 2020-09-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airpoll', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='n', max_length=200),
            preserve_default=False,
        ),
    ]
