# Generated by Django 3.1.1 on 2020-09-25 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airpoll', '0006_auto_20200925_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='airpoll.contact'),
        ),
    ]
